import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.PasswordField;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import jdk.nashorn.internal.codegen.CompilerConstants.Call;
import net.connectcode.Code128Auto;
import static org.eclipse.persistence.platform.database.oracle.plsql.OraclePLSQLTypes.Int;

/**
 *
 * @author Ayoub
 */
public class index extends javax.swing.JFrame {

   // public static   String q = ""  ;
                 
     static final String JDBC_DRIVER="com.mysql.jdbc.Driver";
     static final String DB_URL = "jdbc:mysql://localhost/stor";
     static final String USER = "root";
     static final String PASS = "";
    public index() {
        

       this.setSize(1370, 730);
        initComponents();
        
        
     /*   random random_namber = new random();
        long m =random_namber.a();
         
                 q=Long.toString(m);
             
        Code128Auto a = new Code128Auto();
        
        String b = a.encode(q);
        jLabel4.setText(b);
        jLabel4.setFont(new java.awt.Font("CCode128_S3_Trial", java.awt.Font.PLAIN, 30));
       */ 
    }
  public index(String prar) {
       initComponents();
       saller.setText(prar);
       
       
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_p = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        P_selling_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        P_Quantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        show_sum = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        P_id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        name = new javax.swing.JLabel();
        saller = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("المبيعات ");

        jButton1.setText("بيع و طباعة الفاتورة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("الأسم");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("سعر المنتج ");

        show_p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_p.setText("السعر ");
        show_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("قيمة البيع");

        P_selling_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P_selling_price.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("عدد القطع ");

        P_Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P_Quantity.setPreferredSize(new java.awt.Dimension(60, 20));
        P_Quantity.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                P_QuantityMouseMoved(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("المجموع ");

        show_sum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_sum.setText("القيمة * القطع");
        show_sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_sumMouseClicked(evt);
            }
        });

        jButton2.setText("تسجيل الخروج");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("الكود");

        P_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P_id.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                P_idMouseMoved(evt);
            }
        });
        P_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_idActionPerformed(evt);
            }
        });

        jButton3.setText("تعديل الفاتورة");

        jButton4.setText("إضافة للفاتورة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "الكود", "الأسم", "السعر", "العدد", "المجموع"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        saller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(saller, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                        .addComponent(show_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(show_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(292, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(P_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(P_selling_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saller, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(show_p, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new test_Login().setVisible(true);
                     this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void P_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_idActionPerformed
     File f= new File("C:\\Users\\alhas\\Desktop\\1");
     Workbook wb=Workbook.getWorkbook(f);
    Sheet s=wb.getSheet(0);
      int row=s.getRows();
      int col=s.getColums();
      for(int i=0;i<row;i++){
          Call c=s.getCall(0,i);
      }
      
      
      
      


    }//GEN-LAST:event_P_idActionPerformed

    private void show_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pMouseClicked
         
        
    }//GEN-LAST:event_show_pMouseClicked

    private void show_sumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_sumMouseClicked
      
            int s= Integer.parseInt(P_selling_price.getText());
            int q= Integer.parseInt(P_Quantity.getText());
        
       int sum = s * q;
       String sum_S=String.valueOf(sum);
       show_sum.setText(sum_S);
     
    }//GEN-LAST:event_show_sumMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

      DefaultTableModel dmt =new DefaultTableModel();
        jTable1.setModel(dmt);
        
         dmt.addColumn(" code ");
        dmt.addColumn(" name ");
        dmt.addColumn(" price ");
        dmt.addColumn(" Quantity ");
        dmt.addColumn(" sum ");
       
        
        Connection conn = null;
        Statement stmt =null;
              
                
            // Connection conn = null;
             PreparedStatement pstmt =null;
        try{
            
            Class.forName(JDBC_DRIVER);
            conn=DriverManager.getConnection(DB_URL, USER, PASS);
            
            String sql ="insert into  vatora "
                    + "( code , name  , price , Quantity , sum  ) "
                    + "values( ? , ? , ? , ? , ?   )";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, P_id.getText());
            pstmt.setString(2, name.getText());
            pstmt.setInt(3, Integer.parseInt(show_p.getText())); 
            pstmt.setInt(4, Integer.parseInt(P_Quantity.getText()));
            pstmt.setInt(5, Integer.parseInt(show_sum.getText()));
            
           
            int rs =pstmt.executeUpdate();
            if(rs>0)
//                JOptionPane.showMessageDialog(null,"date seved ");
            pstmt.close();
            conn.close();
            
        }
        
        
        catch (ClassNotFoundException ex) {
            System.out.println("error 1 ");
        } catch (SQLException ex) {
              System.out.println("error 2 ");
              
        }
        int count=0;
        
        
        Connection con = null;
   
              Date d=new Date();
              SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd / / hh:mm");
              String a = s.format(d);
              System.out.println(s.format(d));
      
              String nam=saller.getText();        
            // Connection conn = null;
             PreparedStatement pstm =null;
        try{
            
            Class.forName(JDBC_DRIVER);
            con=DriverManager.getConnection(DB_URL, USER, PASS);
            
            String sql ="insert into  sall "
                    + "( code , name  , price_supposed ,price_sall  , Quantity , sum ,date , seller_name ,barcode ) "
                    + "values( ? , ? , ? , ? , ? , ? , ?  , ? , ? )";
            pstm = con.prepareStatement(sql);
            pstm.setString(1, P_id.getText());
            pstm.setString(2, name.getText());
            pstm.setDouble(3, Double.parseDouble(show_p.getText())); 
            pstm.setDouble(4, Double.parseDouble(P_selling_price.getText())); 
            pstm.setDouble(5, Double.parseDouble(P_Quantity.getText()));
            pstm.setDouble(6, Double.parseDouble(show_sum.getText()));
            pstm.setString(7, a);
            pstm.setString(8,nam);
             pstm.setString(9,q);

           
            int rs =pstm.executeUpdate();
            if(rs>0)
  //              JOptionPane.showMessageDialog(null,"date seved ");
            pstm.close();
            con.close();
            
        }
        
        
        catch (ClassNotFoundException ex) {
            System.out.println("error 1 ");
        } catch (SQLException ex) {
              System.out.println("error 2 ");
              
        }
       
       
        
        
        
         try{
            Class.forName(JDBC_DRIVER);
            conn=DriverManager.getConnection(DB_URL, USER, PASS);
            stmt= conn.createStatement();
            
            String sql ="Select code , name , price , Quantity , sum  from  vatora ";
            //"(E_id_n , E_name , E_age , E_Nationality , E_phone_number , E_address , E_startdate , E_notes ) "
            ResultSet r = stmt.executeQuery(sql);
           
            while (r.next()) {
                Object arry[] = {r.getString("code"),
                                 r.getString("name"),
                                 r.getInt("price"),
                                 r.getInt("Quantity"),
                                 r.getInt("sum"),
                              
                                 
                                 };
                dmt.addRow(arry);
                }
            r.close();
            stmt.close();
            conn.close();
            }
        catch (ClassNotFoundException ex) {
            System.out.println("error 1 ");
        } catch (SQLException ex) {
            System.out.println("error 2 ");
        }                
         
                
                
                
    }//GEN-LAST:event_jButton4ActionPerformed

     public static   String q = ""  ;
       //  q=Long.toString(z);
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         
        // add to table sall
       
         long z = (long) (300000*Math.random()*500000);
           
        
                 q=Long.toString(z);
             
        Code128Auto a = new Code128Auto();
        
        String b = a.encode(q);
        jLabel4.setText(b);
        jLabel4.setFont(new java.awt.Font("CCode128_S3_Trial", java.awt.Font.PLAIN, 30));

        
        
         
        try {                                         
            
            Connection conn = null;
            Statement stmt = null;
            try {
                //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
                //STEP 3: Open a connection
                System.out.println("Connecting to a selected database...");
                conn = DriverManager.getConnection(DB_URL, USER, PASS);
                System.out.println("Connected database successfully...");
                
                //STEP 4: Execute a query
                System.out.println("Creating statement...");
                stmt = conn.createStatement();
                String sql = "DELETE FROM vatora";
                
                
                stmt.executeUpdate(sql);
                
                //STEP 6: Close resources
                stmt.close();
                conn.close();
            } 
            catch (ClassNotFoundException | SQLException ex) {
                //Handle errors for Class.forName and for JDBC
                System.out.println("ayoub");
            }
            boolean c=jTable1.print();
            if(c){
               JOptionPane.showMessageDialog(null,"Done printing");
                
                
            }
            else{
                JOptionPane.showMessageDialog(null, "print");
            }
            
            // TODO add your handling code here:
        } catch (PrinterException ex) {
             System.out.println("PrinterException");
        }
        
        
        
        
        
         DefaultTableModel dmt =new DefaultTableModel();
        jTable1.setModel(dmt);
        
         dmt.addColumn(" code ");
        dmt.addColumn(" name ");
        dmt.addColumn(" price ");
        dmt.addColumn(" Quantity ");
        dmt.addColumn(" sum ");
        
                Connection conna = null;
            Statement stmta = null;
          try{
            Class.forName(JDBC_DRIVER);
            conna=DriverManager.getConnection(DB_URL, USER, PASS);
            stmta= conna.createStatement();
            
            String sql ="Select code , name , price , Quantity , sum  from  vatora ";
            //"(E_id_n , E_name , E_age , E_Nationality , E_phone_number , E_address , E_startdate , E_notes ) "
            ResultSet r = stmta.executeQuery(sql);
           
            while (r.next()) {
                Object arry[] = {r.getString("code"),
                                 r.getString("name"),
                                 r.getInt("price"),
                                 r.getInt("Quantity"),
                                 r.getInt("sum"),
                              
                                 
                                 };
                dmt.addRow(arry);
                }
            r.close();
            stmta.close();
            conna.close();
            }
        catch (ClassNotFoundException ex) {
            System.out.println("error 1 ");
        } catch (SQLException ex) {
            System.out.println("error 2 ");
        }                
         
       P_id.setText("");
       name.setText("");
       show_p.setText("");
       P_selling_price.setText("");
       P_Quantity.setText("");
       show_sum.setText("القيمة * القطع");
        
        
       
       
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  try{
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
     int SelectedRowIndex=jTable1.getSelectedRow();
     model.removeRow(SelectedRowIndex);
   }catch(Exception ex){
       JOptionPane.showMessageDialog(null, ex);
   
   } 
        try{   PreparedStatement pstm =null;
            Connection c = DriverManager.getConnection(DB_URL, USER, PASS);
            String Sql="delete from vatora where code=?";
        pstm = c.prepareStatement(Sql);
         pstm.setString(1, P_id.getText());
        pstm.execute();
         JOptionPane.showMessageDialog(null, "delet");
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
     
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void P_QuantityMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_QuantityMouseMoved
        // mouse Moved 

         int s= Integer.parseInt(P_selling_price.getText());
            int q= Integer.parseInt(P_Quantity.getText());
        
       int sum = s * q;
       String sum_S=String.valueOf(sum);
       show_sum.setText(sum_S);

        
    }//GEN-LAST:event_P_QuantityMouseMoved

    private void P_idMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_idMouseMoved

        
        
        Statement stmt =null;
    Connection conn = null;
             PreparedStatement pstmt =null;
        try{
            Class.forName(JDBC_DRIVER);
            conn=DriverManager.getConnection(DB_URL, USER, PASS);
             stmt= conn.createStatement();
            String sql ="Select P_selling_price , P_name from  products WHERE P_id = ? " ;
            
            pstmt = conn.prepareStatement(sql);
            pstmt.setDouble(1, Double.parseDouble(P_id.getText()));
           
            
           
            ResultSet rs= pstmt.executeQuery();
            //  ResultSet rs = stmt.executeQuery(sql);
            
                  while (rs.next()) {
                      
                    int price= rs.getInt("P_selling_price");
                    String nam =rs.getString("P_name");
                      String price_S=String.valueOf(price);
                      show_p.setText(price_S);
                      name.setText(nam);
                
                //JOptionPane.showMessageDialog(null,"date seved ");
                  }
            
            pstmt.close();
            conn.close();
            
        }
        catch (ClassNotFoundException ex) {
            System.out.println("error 1 ");
        } catch (SQLException ex) {
              System.out.println("error 2 ");
              
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_P_idMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_Quantity;
    private javax.swing.JTextField P_id;
    private javax.swing.JTextField P_selling_price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel saller;
    private javax.swing.JLabel show_p;
    private javax.swing.JLabel show_sum;
    // End of variables declaration//GEN-END:variables
}
